- name: test
  hosts: all

  vars:
    services:
      - NameNode
      - ApplicationHistoryServer
      - NodeManage
      - ResourceManager
      - datanode
  tasks:
    - name: Check url
      uri:
        url: http://192.168.0.150:9870
      register: _result
      ignore_errors: true
    - name: Test ps ef
      shell: "ps -ef"
      register: this
    - debug: msg="{{ services }} not started"
      when: "'{{ services }}' not in this.stdout"
    - debug: msg="http://192.168.0.150:9870 не доступен по данному порту"
      when: _result.status != 200
    - debug: msg="Проверяем продолжать выполенние или нет"
      failed_when:
        - "'{{ services }}' not in this.stdout"
        - "_result.status != 200"